import { ReactQueryProvider } from "@/components/ReactQueryProvider";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { PropsWithChildren } from "react";
import "./globals.css";
import { ModalPlacer } from "@/extra/modal";
config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: PropsWithChildren) {
  const { children } = props;

  return (
    <html lang="en">
      <body
        className={`${inter.className} flex h-screen bg-gradient-to-b from-orange-200 to-green-200`}
      >
        <ReactQueryProvider>
          {children}
          <ModalPlacer />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
