import { ModalPlacer } from "@/components/ModalPlacer";
import { ModalProvider } from "@/components/ModalProvider";
import { ReactQueryProvider } from "@/components/ReactQueryProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { PropsWithChildren } from "react";
import "./globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: PropsWithChildren) {
  const { children } = props;

  return (
    <html lang='en'>
      <body
        className={`${inter.className} bg-gradient-to-b from-orange-200 to-green-200 w-screen min-h-screen`}
      >
        <ModalProvider>
          <ReactQueryProvider>
            {children}
            <ModalPlacer />
          </ReactQueryProvider>
        </ModalProvider>
      </body>
    </html>
  );
}
